apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vq8gj06je-java-springboot
  janus-idp.io/tekton: vq8gj06je-java-springboot
  backstage.io/kubernetes-id: vq8gj06je-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vq8gj06je-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
